export default [
    {
        "id": 1,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1569534038640-69a6a85e9adf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 455.99
        },
        "rating": 5,
    },
    {
        "id": 2,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1552562739-152fee1f81f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=332&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 24,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 469.99,
            "sale_amount": 249.99
        },
        "rating": 5,
    },
    {
        "id": 3,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1544642899-f0d6e5f6ed6f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 455.99
        },
        "rating": 5,
    },
    {
        "id": 4,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1548286978-a0b1e5ff958f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 455.99
        },
        "rating": 5,
    },
    {
        "id": 5,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1552057008-518700a52ad0?ixlib=rb-1.2.1&auto=format&fit=crop&w=401&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 455.99
        },
        "rating": 5,
    },
    {
        "id": 6,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.pexels.com/photos/1460036/pexels-photo-1460036.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 7,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1554526735-d80ab4e7e578?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 8,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1554596393-721d3d7d604c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=305&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 9,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1573220489275-2704adc34a1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 10,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1549399239-fb3c102d3d71?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 11,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1516431762806-5a41e2353ae4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=375&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 12,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1570457465773-0b33c35ddbad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    },
    {
        "id": 13,
        "sale": true,
        "name": "Black Syntetic Jacket",
        "description": "",
        "image": "https://images.unsplash.com/photo-1553717625-3bbeb1e2f5c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80",
        "product_type": "shoes",
        "created_at": "2020-02-03T21:17:23.829Z",
        "options": {
            "material": "syntetic",
            "size": ["sm", "md"],
            "color": "black",
        },
        "stock": 30,
        "tags": [],
        "price": {
            "currency_code": "GBP",
            "amount": 499.99,
            "sale_amount": 299.99,
        },
        "rating": 5,
    }
]